# 实验性代码的存档
这里是一些实验性代码的存档，因为源数据过大，很多时候需要用笔算能验算的样本数据验证一边。
每份代码都会有对应的使用地方和对应的说明

In [9]:
#自动同步外界模组
# Some more magic so that the notebook will reload external python modules;
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [1]:
#########################################
#将一个键值对数组根据键值对中的值排序   #
#########################################
import numpy as np
test={1: 3, 2: 2, 3: 6}
test=sorted(test.items(),key=lambda t:t[1],reverse=True)
test[0][0]


3

## knn数组实现的实验过程

``` python
>>> import numpy
>>> import numpy as np
>>> a=np.array([[1,2,3],[4,5,6],[7,8,9]])
>>> b=np.array([[1,1,1],[2,2,2]])
>>> a
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
>>> b
array([[1, 1, 1],
       [2, 2, 2]])
>>> c=b.dot(a.T)
>>> c
array([[ 6, 15, 24],
       [12, 30, 48]])
>>> c=-2*c
>>> c
array([[-12, -30, -48],
       [-24, -60, -96]])
>>> np.square(b)
array([[1, 1, 1],
       [4, 4, 4]], dtype=int32)
>>> bSum=np.square(b)
>>> bSum
array([[1, 1, 1],
       [4, 4, 4]], dtype=int32)
>>> bSum.sum(axis=1)
array([ 3, 12], dtype=int32)
>>> bSum=bSum.sum(axis=1)
>>> bSum.reshape((1,2))
array([[ 3, 12]], dtype=int32)
>>> b+c
array([[-11, -29, -47],
       [-22, -58, -94]])
>>> bSum
array([ 3, 12], dtype=int32)
>>> np.reshape(bSum,(1,2))
array([[ 3, 12]], dtype=int32)
>>> bSum
array([ 3, 12], dtype=int32)
>>> bSum=bSum.reshape((1,2))
>>> bSum
array([[ 3, 12]], dtype=int32)
>>> bSum=bSum.T
>>> bSum
array([[ 3],
       [12]], dtype=int32)
>>> c=bSum+c
>>> c
array([[ -9, -27, -45],
       [-12, -48, -84]])
>>> np.square(a).sum(axis=1)
array([ 14,  77, 194], dtype=int32)
>>> a
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
>>> np.square(a).sum(axis=1)+c
array([[  5,  50, 149],
       [  2,  29, 110]])
>>> a
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
>>> b
array([[1, 1, 1],
       [2, 2, 2]])
>>>
```

In [29]:
##########################################
#利用np.array_split对一个数组进行均分    #
##########################################
import numpy as np
splitTest=np.arange(8)
splitTest=np.array_split(splitTest,5)
splitTest

[array([0, 1]), array([2, 3]), array([4, 5]), array([6]), array([7])]

In [17]:
#######################################
#利用hstack对一个数组不同的数组进行   #
#拼接，注意hstack接收的是由括号括起来 #
#的一连串数组                         #
#######################################
np.hstack((splitTest[0:1]+splitTest[2:]))

NameError: name 'splitTest' is not defined

In [5]:
######np.arange特殊的用法#################
#arange如果是从大到小的话需要填负数的步长#
##########################################
np.arange(10,1,-1)


array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [14]:
############################
#一种快速求结果正确率的方法#
############################
y_pred=np.array([0,0,1])
y_true=np.array([0,0,0])
print(y_pred==y_true)
np.mean(y_pred==y_true)

[ True  True False]


0.6666666666666666

## SVM 向量化实现

In [1]:
#初始化
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([0,1,0])
W=np.array([[2,3,1],[1,2,3]]).T
print("X:",X.shape)
print("y:",y.shape)
print("W:",W.shape)

X: (3, 3)
y: (3,)
W: (3, 2)


In [54]:
#进行原数据与权重矩阵的相乘
score=X.dot(W)
score

array([[11, 14],
       [29, 32],
       [47, 50]])

In [51]:
y=y.reshape(-1,3)
y
y.shape

(1, 3)

In [52]:
score_of_true_label=score[range(0,3),y]
score_of_true_label

array([[11, 32, 47]])

In [39]:
first_sum=score-score_of_true_label.T+1
first_sum

array([[ 1,  4],
       [-2,  1],
       [ 1,  4]])

In [42]:
first_sum[first_sum<0]=0
first_sum

array([[1, 4],
       [0, 1],
       [1, 4]])

In [47]:
second_sum=first_sum.sum(axis=1)-1

In [49]:
former_sum=second_sum.sum()

# 小规模测试

In [3]:
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([0,1,0])
W=np.array([[2,3,1],[1,2,3]]).T
print("X:",X.shape)
print("y:",y.shape)
print("W:",W.shape)

X: (3, 3)
y: (3,)
W: (3, 2)


In [4]:
from cs231n.classifiers.linear_svm import svm_loss_vectorized,svm_loss_naive
print(svm_loss_naive(W,X,y,0.05))
print(svm_loss_vectorized(W,X,y,0.05))

(4.066666666666666, array([[-2.46666667,  2.76666667],
       [-3.03333333,  3.53333333],
       [-3.9       ,  4.3       ]]))
[[0 1]
 [0 0]
 [0 1]]
[-1  0 -1]
[[-1  1]
 [ 0  0]
 [-1  1]]
(4.066666666666666, array([[-2.46666667,  2.76666667],
       [-3.03333333,  3.53333333],
       [-3.9       ,  4.3       ]]))


# 梯度实验

In [3]:
#初始化
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([0,1,0])
W=np.array([[2,3,1],[1,2,3]]).T
print("X:",X.shape)
print("y:",y.shape)
print("W:",W.shape)
score=X.dot(W)
y=y.reshape(-1,3)
score_of_true_label=score[range(0,3),y]
first_sum=score-score_of_true_label.T+1
first_sum[first_sum<0]=0
first_sum[np.arange(3),y]=0
first_sum

X: (3, 3)
y: (3,)
W: (3, 2)


array([[0, 4],
       [0, 0],
       [0, 4]])

In [8]:
print("X:\n",X,"\nW:\n",W)

X:
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
W:
 [[2 1]
 [3 2]
 [1 3]]


In [4]:
first_sum.astype(int)

array([[0, 4],
       [0, 0],
       [0, 4]])

# 分类测试

In [3]:
#初始化
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([0,1,0])
W=np.array([[2,3,1],[1,2,3]]).T
print("X:",X.shape)
print("y:",y.shape)
print("W:",W.shape)
score=X.dot(W)
score

X: (3, 3)
y: (3,)
W: (3, 2)


array([[11, 14],
       [29, 32],
       [47, 50]])

In [4]:
score.argmax(axis=1)

array([1, 1, 1], dtype=int64)

# 调整超参数实验

In [5]:
learning_rates = [1e-7, 5e-6]
regularization_strengths = [5e4, 1e5]
for lr in learning_rates:
    for reg in regularization_strengths:
        print(lr, reg)

1e-07 50000.0
1e-07 100000.0
5e-06 50000.0
5e-06 100000.0


# Softmax实验

In [44]:
#初始化
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([0,1,0])
W=np.array([[2,3,1],[1,2,3]]).T
print("X:",X.shape)
print("y:",y.shape)
print("W:",W.shape)
score=X.dot(W)
print(score-score.max())
score=np.power(np.exp(1),score-score.max())
print(score,"\n")
print(score.sum(axis=1).reshape((3,1)).dot(np.ones((1,2))))
score=score/score.sum(axis=1).reshape((3,1)).dot(np.ones((1,2)))
loss=-np.log(score)[np.arange(3),y]
loss/=3
loss


X: (3, 3)
y: (3,)
W: (3, 2)
[[-39 -36]
 [-21 -18]
 [ -3   0]]
[[1.15482242e-17 2.31952283e-16]
 [7.58256043e-10 1.52299797e-08]
 [4.97870684e-02 1.00000000e+00]] 

[[2.43500507e-16 2.43500507e-16]
 [1.59882358e-08 1.59882358e-08]
 [1.04978707e+00 1.04978707e+00]]


array([1.01619578, 0.01619578, 1.01619578])

In [29]:
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([1,2,3]).T.reshape(3,1).dot(np.ones((1,3)))
X/y

array([[1.        , 2.        , 3.        ],
       [2.        , 2.5       , 3.        ],
       [2.33333333, 2.66666667, 3.        ]])

# 矩阵筛选实验

In [3]:
import numpy as np
y = np.arange(35).reshape(5,7)
y[y>10]=0
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

# tensorflow运行实验

In [4]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(512, activation=tf.nn.relu),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)


11493376/11490434 [==============================] - 4s 0us/step
Epoch 1/5
60000/60000 [==============================] - 10s 167us/step - loss: 0.1989 - acc: 0.9410
Epoch 2/5
60000/60000 [==============================] - 7s 120us/step - loss: 0.0798 - acc: 0.9756
Epoch 3/5
60000/60000 [==============================] - 7s 121us/step - loss: 0.0525 - acc: 0.9829
Epoch 4/5
60000/60000 [==============================] - 7s 119us/step - loss: 0.0371 - acc: 0.9881
Epoch 5/5
10000/10000 [==============================] - 1s 92us/step


[0.07032331763250986, 0.9801]

In [2]:
import tensorflow as tf
import numpy as np
import time
shape = (10000,10000)

# /cpu:0 ... first available CPU
# /gpu:0 ... first available GPU

with tf.device("/gpu:0"):
    random_matrix = tf.random_uniform(shape)
    matrix_multiply = tf.matmul(random_matrix,tf.transpose(random_matrix))
    sum_of_result = tf.reduce_sum(matrix_multiply)

t_start = time.time()
with tf.Session() as session:
    result = session.run(sum_of_result)

t_stop = time.time()
t_passed = t_stop - t_start
print('Elapsed time: {} s'.format(t_passed))
print(result)

Elapsed time: 0.9944236278533936 s
249995540000.0


# 随意测试

In [6]:
import numpy as np
?np.mean